layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: 
    - pushed
      stars
  limit: 7
  exclude:
    projects:
      - benwtrent.github.io 
      - paip-clj 

social_media:
  stackoverflow: 1818849
  twitter: benwtrent
  linkedin: benjamin-trent

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://images.contentstack.io/v3/assets/bltefdd0b53724fa2ce/bltfa7a3570a287d7ec/5c11d9ada6ed043c0dbb01a9/icon-machine-learning-bb.svg

  - name: Clojure
    web_url: https://github.com/topics/clojure
    image_url: https://raw.githubusercontent.com/github/explore/a4f50275e9736bcd9f255084c4908627f5dd9069/topics/clojure/clojure.png
  
  - name: Elasticsearch
    web_url: https://github.com/elastic/elasticsearch
    image_url: https://images.contentstack.io/v3/assets/bltefdd0b53724fa2ce/blt280217a63b82a734/5bbdaacf63ed239936a7dd56/elastic-logo.svg
