layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
     # - repo-name

social_media:
  # behance: your_username
  dribbble: jsmiith
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  medium: jsmiith
  stackoverflow: 10274252
  # telegram: your_username
  twitter: jsmiiiiith
  unsplash: jsmiith
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username