layout: stacked
style: light

include: ['_pages']

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars

  # Optional limit
  # limit: 9

  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name
