layout: sidebar
style: light
theme: jekyll-theme-hacker


plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-admin
permalink: /:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  website: https://filiptronicek.github.io/
  twitter: filiptronicek
  stackoverflow: 10199319
  facebook: filiptronicek69
  hackerrank: filip_tronicek
  instagram: filiptronicek93

topics:
  
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png

  - name: PHP
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/ccc16358ac4530c6a69b1b80c7223cd2744dea83/topics/php/php.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png


